/**
 * Official Server-Side Menu Pricing & Crust Catalog.
 * Used for Backend Price Validation & Anti-Tampering Protection.
 */

export const SERVER_MENU_PRICES: Record<string, { name: string; price: number; category: string }> = {
  // Tradicionais
  "abobrinha": { name: "Abobrinha", price: 48, category: "tradicionais" },
  "alho": { name: "Alho", price: 48, category: "tradicionais" },
  "atum": { name: "Atum", price: 48, category: "tradicionais" },
  "bacon": { name: "Bacon", price: 48, category: "tradicionais" },
  "baianinha": { name: "Baianinha", price: 48, category: "tradicionais" },
  "bauru": { name: "Bauru", price: 46, category: "tradicionais" },
  "bragantina": { name: "Bragantina", price: 50, category: "tradicionais" },
  "brasileira": { name: "Brasileira", price: 48, category: "tradicionais" },
  "brocolis": { name: "Brócolis", price: 48, category: "tradicionais" },
  "calabresa": { name: "Calabresa", price: 48, category: "tradicionais" },
  "calabria": { name: "Calábria", price: 48, category: "tradicionais" },
  "caicara": { name: "Caiçara", price: 46, category: "tradicionais" },
  "carijo": { name: "Carijó", price: 48, category: "tradicionais" },
  "do-chef": { name: "Do Chef", price: 50, category: "tradicionais" },
  "elite": { name: "Elite", price: 48, category: "tradicionais" },
  "escarola": { name: "Escarola", price: 48, category: "tradicionais" },
  "francesa": { name: "Francesa", price: 48, category: "tradicionais" },
  "frango-mussarela": { name: "Frango Mussarela", price: 46, category: "tradicionais" },
  "frango-catupiry": { name: "Frango com Catupiry", price: 46, category: "tradicionais" },
  "frango-bicolor": { name: "Frango Bicolor", price: 48, category: "tradicionais" },
  "frango-cheddar": { name: "Frango e Cheddar", price: 48, category: "tradicionais" },
  "imperio": { name: "Império", price: 48, category: "tradicionais" },
  "jardineira": { name: "Jardineira", price: 48, category: "tradicionais" },
  "lombo": { name: "Lombo", price: 48, category: "tradicionais" },
  "marguerita": { name: "Marguerita", price: 46, category: "tradicionais" },
  "milho": { name: "Milho", price: 46, category: "tradicionais" },
  "mussarela": { name: "Mussarela", price: 46, category: "tradicionais" },
  "napolitana": { name: "Napolitana", price: 48, category: "tradicionais" },
  "palmito": { name: "Palmito", price: 48, category: "tradicionais" },
  "paulista": { name: "Paulista", price: 48, category: "tradicionais" },
  "picardia": { name: "Picardia", price: 48, category: "tradicionais" },
  "portuguesa": { name: "Portuguesa", price: 50, category: "tradicionais" },
  "toscana": { name: "Toscana", price: 48, category: "tradicionais" },
  "vegetariana": { name: "Vegetariana", price: 50, category: "tradicionais" },
  "2-queijos": { name: "2 Queijos", price: 48, category: "tradicionais" },
  "3-queijos": { name: "3 Queijos", price: 50, category: "tradicionais" },
  "4-queijos": { name: "4 Queijos", price: 52, category: "tradicionais" },

  // Especiais
  "atum-especial": { name: "Atum Especial", price: 55, category: "especiais" },
  "baiana": { name: "Baiana", price: 60, category: "especiais" },
  "brocolis-branco": { name: "Brócolis ao Molho Branco", price: 55, category: "especiais" },
  "classica": { name: "Clássica", price: 68, category: "especiais" },
  "do-pizziolo": { name: "Do Pizziolo", price: 55, category: "especiais" },
  "escondidinho": { name: "Escondidinho de Carne Seca", price: 68, category: "especiais" },
  "especial-casa": { name: "Especial da Casa", price: 55, category: "especiais" },
  "linguica-artesanal": { name: "Linguiça Artesanal", price: 48, category: "especiais" },
  "mineira": { name: "Mineira", price: 55, category: "especiais" },
  "moda-casa": { name: "Moda da Casa", price: 55, category: "especiais" },
  "nordestina": { name: "Nordestina", price: 68, category: "especiais" },
  "peruana": { name: "Peruana", price: 68, category: "especiais" },
  "pepperoni": { name: "Pepperoni", price: 60, category: "especiais" },
  "portuguesa-chefe": { name: "Portuguesa do Chefe", price: 66, category: "especiais" },
  "pizza-hotdog": { name: "Pizza Hot Dog", price: 55, category: "especiais" },
  "rucula": { name: "Rúcula", price: 55, category: "especiais" },
  "strogonoff-carne": { name: "Strogonoff de Carne", price: 58, category: "especiais" },
  "strogonoff-frango": { name: "Strogonoff de Frango", price: 55, category: "especiais" },
  "vip": { name: "VIP", price: 55, category: "especiais" },
  "5-queijos": { name: "5 Queijos", price: 58, category: "especiais" },
  "6-queijos": { name: "6 Queijos", price: 60, category: "especiais" },

  // Doces
  "banana": { name: "Banana", price: 46, category: "doces" },
  "banana-nevada": { name: "Banana Nevada", price: 48, category: "doces" },
  "bis-oreo": { name: "Bis de Oreo", price: 48, category: "doces" },
  "brigadeiro": { name: "Brigadeiro", price: 46, category: "doces" },
  "confete": { name: "Confete", price: 46, category: "doces" },
  "choconana": { name: "Choconana", price: 48, category: "doces" },
  "ouro-branco": { name: "Ouro Branco", price: 48, category: "doces" },
  "sonho-valsa": { name: "Sonho de Valsa", price: 48, category: "doces" },
  "romeu-julieta": { name: "Romeu e Julieta", price: 46, category: "doces" },
  "prestigio": { name: "Prestígio", price: 46, category: "doces" },
  "sensacao": { name: "Sensação", price: 48, category: "doces" },
  "uva-verde": { name: "Uva Verde", price: 48, category: "doces" },

  // Doces Especiais
  "leite-ninho": { name: "Leite Ninho", price: 58, category: "doces-especiais" },
  "pistache": { name: "Pistache", price: 55, category: "doces-especiais" },
  "nutella": { name: "Nutella", price: 66, category: "doces-especiais" },
  "morango-supreme": { name: "Morango Supreme", price: 66, category: "doces-especiais" },
  "floresta-negra": { name: "Floresta Negra", price: 68, category: "doces-especiais" },

  // Brotos
  "broto-tradicional": { name: "Broto Tradicional", price: 34, category: "brotos" },
  "broto-especial": { name: "Broto Especial", price: 40, category: "brotos" },

  // Bebidas
  "coca-2l": { name: "Coca-Cola 2L", price: 16, category: "bebidas" },
  "guarana-2l": { name: "Guaraná 2L", price: 15, category: "bebidas" },
  "sprite-2l": { name: "Sprite 2L", price: 15, category: "bebidas" },
  "fanta-laranja-2l": { name: "Fanta Laranja 2L", price: 15, category: "bebidas" },
  "fanta-uva-2l": { name: "Fanta Uva 2L", price: 15, category: "bebidas" },
  "mantovani-2l": { name: "Mantovani 2L", price: 10, category: "bebidas" },
  "coca-lata": { name: "Coca-Cola Lata", price: 6, category: "bebidas" },
  "guarana-lata": { name: "Guaraná Lata", price: 6, category: "bebidas" },
  "sprite-lata": { name: "Sprite Lata", price: 6, category: "bebidas" },
  "fanta-laranja-lata": { name: "Fanta Laranja Lata", price: 6, category: "bebidas" },
  "fanta-uva-lata": { name: "Fanta Uva Lata", price: 6, category: "bebidas" },
  "suco-delvalle-lata": { name: "Suco Del Valle Lata 290ml", price: 3.5, category: "bebidas" },
  "suco-delvalle-1l": { name: "Suco Del Valle 1L", price: 7, category: "bebidas" },
  "agua-sem-gas": { name: "Água Mineral 500ml", price: 3.5, category: "bebidas" },
  "agua-com-gas": { name: "Água com Gás 500ml", price: 4, category: "bebidas" },
  "itaipava": { name: "Cerveja Itaipava 350ml", price: 5, category: "bebidas" },
  "skol": { name: "Cerveja Skol 350ml", price: 6, category: "bebidas" },
  "imperio-cerveja": { name: "Cerveja Império 350ml", price: 6, category: "bebidas" },
  "puro-malte": { name: "Cerveja Puro Malte 350ml", price: 7, category: "bebidas" },
  "heineken": { name: "Cerveja Heineken 350ml", price: 8, category: "bebidas" },
  "vinho-artesanal": { name: "Vinho Artesanal 1L", price: 28, category: "bebidas" },

  // Adicionais
  "ad-catupiry": { name: "Catupiry Original", price: 5, category: "adicionais" },
  "ad-cheddar": { name: "Cheddar", price: 7, category: "adicionais" },
  "ad-bacon": { name: "Bacon", price: 7, category: "adicionais" },
  "ad-cebola": { name: "Cebola", price: 4, category: "adicionais" },
  "ad-tomate": { name: "Tomate", price: 4, category: "adicionais" },
  "ad-ovos": { name: "Ovos", price: 4, category: "adicionais" },
  "ad-batata-palha": { name: "Batata Palha", price: 8, category: "adicionais" },
  "ad-azeitona": { name: "Azeitona Preta", price: 6, category: "adicionais" },
  "ad-milho": { name: "Milho", price: 5, category: "adicionais" },
};

export const SERVER_CRUST_PRICES: Record<string, { name: string; price: number }> = {
  "nenhuma": { name: "Sem Borda Recheada", price: 0 },
  "catupiry": { name: "Borda Catupiry Original", price: 5 },
  "cheddar": { name: "Borda Cheddar Cremoso", price: 7 },
  "chocolate": { name: "Borda Chocolate ao Leite", price: 7 },
  "doce-leite": { name: "Borda Doce de Leite", price: 7 },
};
